# Changes here will be overwritten by Copier
_commit: 1.1.0
_src_path: gh:pawamoy/copier-uv
author_email: dev@pawamoy.fr
author_fullname: Timothée Mazzucotelli
author_username: pawamoy
copyright_date: '2020'
copyright_holder: Timothée Mazzucotelli
copyright_holder_email: dev@pawamoy.fr
copyright_license: ISC License
insiders: false
project_description: Automatic Changelog generator using Jinja2 templates.
project_name: git-changelog
python_package_command_line_name: git-changelog
python_package_distribution_name: git-changelog
python_package_import_name: git_changelog
repository_name: git-changelog
repository_namespace: pawamoy
repository_provider: github.com

